const binding = require('../binding')
const errors = require('./errors')

function makeTag(a, b, c, d) {
  return (
    a.charCodeAt(0) |
    (b.charCodeAt(0) << 8) |
    (c.charCodeAt(0) << 16) |
    (d.charCodeAt(0) << 24)
  )
}

module.exports = exports = {
  codecs: {
    MJPEG: binding.AV_CODEC_ID_MJPEG,
    AAC: binding.AV_CODEC_ID_AAC,
    OPUS: binding.AV_CODEC_ID_OPUS,
    AV1: binding.AV_CODEC_ID_AV1,
    FLAC: binding.AV_CODEC_ID_FLAC,
    MP3: binding.AV_CODEC_ID_MP3
  },
  tags: {
    MJPEG: makeTag('M', 'J', 'P', 'G'),
    AV1: makeTag('A', 'V', '0', '1'),
    AAC: 0x00ff,
    FLAC: 0xf1ac,
    MP3: 0x0055
  },
  profiles: {
    UNKNOWN: binding.AV_PROFILE_UNKNOWN,
    RESERVED: binding.AV_PROFILE_RESERVED,
    AAC_MAIN: binding.AV_PROFILE_AAC_MAIN,
    AAC_LOW: binding.AV_PROFILE_AAC_LOW,
    AAC_SSR: binding.AV_PROFILE_AAC_SSR,
    AAC_LTP: binding.AV_PROFILE_AAC_LTP,
    AAC_HE: binding.AV_PROFILE_AAC_HE,
    AAC_HE_V2: binding.AV_PROFILE_AAC_HE_V2,
    AAC_LD: binding.AV_PROFILE_AAC_LD,
    AAC_ELD: binding.AV_PROFILE_AAC_ELD,
    AAC_USAC: binding.AV_PROFILE_AAC_USAC,
    MPEG2_AAC_LOW: binding.AV_PROFILE_MPEG2_AAC_LOW,
    MPEG2_AAC_HE: binding.AV_PROFILE_MPEG2_AAC_HE,
    DNXHD: binding.AV_PROFILE_DNXHD,
    DNXHR_LB: binding.AV_PROFILE_DNXHR_LB,
    DNXHR_SQ: binding.AV_PROFILE_DNXHR_SQ,
    DNXHR_HQ: binding.AV_PROFILE_DNXHR_HQ,
    DNXHR_HQX: binding.AV_PROFILE_DNXHR_HQX,
    DNXHR_444: binding.AV_PROFILE_DNXHR_444,
    DTS: binding.AV_PROFILE_DTS,
    DTS_ES: binding.AV_PROFILE_DTS_ES,
    DTS_96_24: binding.AV_PROFILE_DTS_96_24,
    DTS_HD_HRA: binding.AV_PROFILE_DTS_HD_HRA,
    DTS_HD_MA: binding.AV_PROFILE_DTS_HD_MA,
    DTS_EXPRESS: binding.AV_PROFILE_DTS_EXPRESS,
    DTS_HD_MA_X: binding.AV_PROFILE_DTS_HD_MA_X,
    DTS_HD_MA_X_IMAX: binding.AV_PROFILE_DTS_HD_MA_X_IMAX,
    EAC3_DDP_ATMOS: binding.AV_PROFILE_EAC3_DDP_ATMOS,
    TRUEHD_ATMOS: binding.AV_PROFILE_TRUEHD_ATMOS,
    MPEG2_422: binding.AV_PROFILE_MPEG2_422,
    MPEG2_HIGH: binding.AV_PROFILE_MPEG2_HIGH,
    MPEG2_SS: binding.AV_PROFILE_MPEG2_SS,
    MPEG2_SNR_SCALABLE: binding.AV_PROFILE_MPEG2_SNR_SCALABLE,
    MPEG2_MAIN: binding.AV_PROFILE_MPEG2_MAIN,
    MPEG2_SIMPLE: binding.AV_PROFILE_MPEG2_SIMPLE,
    H264_CONSTRAINED: binding.AV_PROFILE_H264_CONSTRAINED,
    H264_INTRA: binding.AV_PROFILE_H264_INTRA,
    H264_BASELINE: binding.AV_PROFILE_H264_BASELINE,
    H264_CONSTRAINED_BASELINE: binding.AV_PROFILE_H264_CONSTRAINED_BASELINE,
    H264_MAIN: binding.AV_PROFILE_H264_MAIN,
    H264_EXTENDED: binding.AV_PROFILE_H264_EXTENDED,
    H264_HIGH: binding.AV_PROFILE_H264_HIGH,
    H264_HIGH_10: binding.AV_PROFILE_H264_HIGH_10,
    H264_HIGH_10_INTRA: binding.AV_PROFILE_H264_HIGH_10_INTRA,
    H264_MULTIVIEW_HIGH: binding.AV_PROFILE_H264_MULTIVIEW_HIGH,
    H264_HIGH_422: binding.AV_PROFILE_H264_HIGH_422,
    H264_HIGH_422_INTRA: binding.AV_PROFILE_H264_HIGH_422_INTRA,
    H264_STEREO_HIGH: binding.AV_PROFILE_H264_STEREO_HIGH,
    H264_HIGH_444: binding.AV_PROFILE_H264_HIGH_444,
    H264_HIGH_444_PREDICTIVE: binding.AV_PROFILE_H264_HIGH_444_PREDICTIVE,
    H264_HIGH_444_INTRA: binding.AV_PROFILE_H264_HIGH_444_INTRA,
    H264_CAVLC_444: binding.AV_PROFILE_H264_CAVLC_444,
    VC1_SIMPLE: binding.AV_PROFILE_VC1_SIMPLE,
    VC1_MAIN: binding.AV_PROFILE_VC1_MAIN,
    VC1_COMPLEX: binding.AV_PROFILE_VC1_COMPLEX,
    VC1_ADVANCED: binding.AV_PROFILE_VC1_ADVANCED,
    MPEG4_SIMPLE: binding.AV_PROFILE_MPEG4_SIMPLE,
    MPEG4_SIMPLE_SCALABLE: binding.AV_PROFILE_MPEG4_SIMPLE_SCALABLE,
    MPEG4_CORE: binding.AV_PROFILE_MPEG4_CORE,
    MPEG4_MAIN: binding.AV_PROFILE_MPEG4_MAIN,
    MPEG4_N_BIT: binding.AV_PROFILE_MPEG4_N_BIT,
    MPEG4_SCALABLE_TEXTURE: binding.AV_PROFILE_MPEG4_SCALABLE_TEXTURE,
    MPEG4_SIMPLE_FACE_ANIMATION: binding.AV_PROFILE_MPEG4_SIMPLE_FACE_ANIMATION,
    MPEG4_BASIC_ANIMATED_TEXTURE:
      binding.AV_PROFILE_MPEG4_BASIC_ANIMATED_TEXTURE,
    MPEG4_HYBRID: binding.AV_PROFILE_MPEG4_HYBRID,
    MPEG4_ADVANCED_REAL_TIME: binding.AV_PROFILE_MPEG4_ADVANCED_REAL_TIME,
    MPEG4_CORE_SCALABLE: binding.AV_PROFILE_MPEG4_CORE_SCALABLE,
    MPEG4_ADVANCED_CODING: binding.AV_PROFILE_MPEG4_ADVANCED_CODING,
    MPEG4_ADVANCED_CORE: binding.AV_PROFILE_MPEG4_ADVANCED_CORE,
    MPEG4_ADVANCED_SCALABLE_TEXTURE:
      binding.AV_PROFILE_MPEG4_ADVANCED_SCALABLE_TEXTURE,
    MPEG4_SIMPLE_STUDIO: binding.AV_PROFILE_MPEG4_SIMPLE_STUDIO,
    MPEG4_ADVANCED_SIMPLE: binding.AV_PROFILE_MPEG4_ADVANCED_SIMPLE,
    JPEG2000_CSTREAM_RESTRICTION_0:
      binding.AV_PROFILE_JPEG2000_CSTREAM_RESTRICTION_0,
    JPEG2000_CSTREAM_RESTRICTION_1:
      binding.AV_PROFILE_JPEG2000_CSTREAM_RESTRICTION_1,
    JPEG2000_CSTREAM_NO_RESTRICTION:
      binding.AV_PROFILE_JPEG2000_CSTREAM_NO_RESTRICTION,
    JPEG2000_DCINEMA_2K: binding.AV_PROFILE_JPEG2000_DCINEMA_2K,
    JPEG2000_DCINEMA_4K: binding.AV_PROFILE_JPEG2000_DCINEMA_4K,
    VP9_0: binding.AV_PROFILE_VP9_0,
    VP9_1: binding.AV_PROFILE_VP9_1,
    VP9_2: binding.AV_PROFILE_VP9_2,
    VP9_3: binding.AV_PROFILE_VP9_3,
    HEVC_MAIN: binding.AV_PROFILE_HEVC_MAIN,
    HEVC_MAIN_10: binding.AV_PROFILE_HEVC_MAIN_10,
    HEVC_MAIN_STILL_PICTURE: binding.AV_PROFILE_HEVC_MAIN_STILL_PICTURE,
    HEVC_REXT: binding.AV_PROFILE_HEVC_REXT,
    HEVC_MULTIVIEW_MAIN: binding.AV_PROFILE_HEVC_MULTIVIEW_MAIN,
    HEVC_SCC: binding.AV_PROFILE_HEVC_SCC,
    VVC_MAIN_10: binding.AV_PROFILE_VVC_MAIN_10,
    VVC_MAIN_10_444: binding.AV_PROFILE_VVC_MAIN_10_444,
    AV1_MAIN: binding.AV_PROFILE_AV1_MAIN,
    AV1_HIGH: binding.AV_PROFILE_AV1_HIGH,
    AV1_PROFESSIONAL: binding.AV_PROFILE_AV1_PROFESSIONAL,
    MJPEG_HUFFMAN_BASELINE_DCT: binding.AV_PROFILE_MJPEG_HUFFMAN_BASELINE_DCT,
    MJPEG_HUFFMAN_EXTENDED_SEQUENTIAL_DCT:
      binding.AV_PROFILE_MJPEG_HUFFMAN_EXTENDED_SEQUENTIAL_DCT,
    MJPEG_HUFFMAN_PROGRESSIVE_DCT:
      binding.AV_PROFILE_MJPEG_HUFFMAN_PROGRESSIVE_DCT,
    MJPEG_HUFFMAN_LOSSLESS: binding.AV_PROFILE_MJPEG_HUFFMAN_LOSSLESS,
    MJPEG_JPEG_LS: binding.AV_PROFILE_MJPEG_JPEG_LS,
    SBC_MSBC: binding.AV_PROFILE_SBC_MSBC,
    PRORES_PROXY: binding.AV_PROFILE_PRORES_PROXY,
    PRORES_LT: binding.AV_PROFILE_PRORES_LT,
    PRORES_STANDARD: binding.AV_PROFILE_PRORES_STANDARD,
    PRORES_HQ: binding.AV_PROFILE_PRORES_HQ,
    PRORES_4444: binding.AV_PROFILE_PRORES_4444,
    PRORES_XQ: binding.AV_PROFILE_PRORES_XQ,
    ARIB_PROFILE_A: binding.AV_PROFILE_ARIB_PROFILE_A,
    ARIB_PROFILE_C: binding.AV_PROFILE_ARIB_PROFILE_C,
    KLVA_SYNC: binding.AV_PROFILE_KLVA_SYNC,
    KLVA_ASYNC: binding.AV_PROFILE_KLVA_ASYNC,
    EVC_BASELINE: binding.AV_PROFILE_EVC_BASELINE,
    EVC_MAIN: binding.AV_PROFILE_EVC_MAIN
  },
  levels: {
    UNKNOWN: binding.AV_LEVEL_UNKNOWN
  },
  pixelFormats: {
    RGBA: binding.AV_PIX_FMT_RGBA,
    RGB24: binding.AV_PIX_FMT_RGB24,
    YUVJ420P: binding.AV_PIX_FMT_YUVJ420P,
    UYVY422: binding.AV_PIX_FMT_UYVY422,
    YUV420P: binding.AV_PIX_FMT_YUV420P
  },
  mediaTypes: {
    UNKNOWN: binding.AVMEDIA_TYPE_UNKNOWN,
    VIDEO: binding.AVMEDIA_TYPE_VIDEO,
    AUDIO: binding.AVMEDIA_TYPE_AUDIO,
    DATA: binding.AVMEDIA_TYPE_DATA,
    SUBTITLE: binding.AVMEDIA_TYPE_SUBTITLE,
    ATTACHEMENT: binding.AVMEDIA_TYPE_ATTACHMENT,
    NB: binding.AVMEDIA_TYPE_NB
  },
  sampleFormats: {
    NONE: binding.AV_SAMPLE_FMT_NONE,
    U8: binding.AV_SAMPLE_FMT_U8,
    S16: binding.AV_SAMPLE_FMT_S16,
    S32: binding.AV_SAMPLE_FMT_S32,
    S64: binding.AV_SAMPLE_FMT_S64,
    FLT: binding.AV_SAMPLE_FMT_FLT,
    DBL: binding.AV_SAMPLE_FMT_DBL,
    U8P: binding.AV_SAMPLE_FMT_U8P,
    S16P: binding.AV_SAMPLE_FMT_S16P,
    S32P: binding.AV_SAMPLE_FMT_S32P,
    S64P: binding.AV_SAMPLE_FMT_S64P,
    FLTP: binding.AV_SAMPLE_FMT_FLTP,
    DBLP: binding.AV_SAMPLE_FMT_DBLP,
    NB: binding.AV_SAMPLE_FMT_NB
  },
  channelLayouts: {
    MONO: binding.AV_CH_LAYOUT_MONO,
    STEREO: binding.AV_CH_LAYOUT_STEREO,
    QUAD: binding.AV_CH_LAYOUT_QUAD,
    SURROUND: binding.AV_CH_LAYOUT_SURROUND,
    2_1: binding.AV_CH_LAYOUT_2POINT1,
    5_0: binding.AV_CH_LAYOUT_5POINT0,
    5_1: binding.AV_CH_LAYOUT_5POINT1,
    7_1: binding.AV_CH_LAYOUT_7POINT1,
    // Aliases
    2.1: binding.AV_CH_LAYOUT_2POINT1,
    '5.0': binding.AV_CH_LAYOUT_5POINT0,
    5.1: binding.AV_CH_LAYOUT_5POINT1,
    7.1: binding.AV_CH_LAYOUT_7POINT1
  },
  pictureTypes: {
    NONE: binding.AV_PICTURE_TYPE_NONE,
    I: binding.AV_PICTURE_TYPE_I,
    P: binding.AV_PICTURE_TYPE_P,
    B: binding.AV_PICTURE_TYPE_B,
    S: binding.AV_PICTURE_TYPE_S,
    SI: binding.AV_PICTURE_TYPE_SI,
    SP: binding.AV_PICTURE_TYPE_SP,
    BI: binding.AV_PICTURE_TYPE_BI
  },
  logLevels: {
    QUIET: binding.AV_LOG_QUIET,
    PANIC: binding.AV_LOG_PANIC,
    FATAL: binding.AV_LOG_FATAL,
    ERROR: binding.AV_LOG_ERROR,
    WARNING: binding.AV_LOG_WARNING,
    INFO: binding.AV_LOG_INFO,
    VERBOSE: binding.AV_LOG_VERBOSE,
    DEBUG: binding.AV_LOG_DEBUG,
    TRACE: binding.AV_LOG_TRACE
  },
  codecFlags: {
    COPY_OPAQUE: binding.AV_CODEC_FLAG_COPY_OPAQUE,
    FRAME_DURATION: binding.AV_CODEC_FLAG_FRAME_DURATION,
    PASS1: binding.AV_CODEC_FLAG_PASS1,
    PASS2: binding.AV_CODEC_FLAG_PASS2,
    LOOP_FILTER: binding.AV_CODEC_FLAG_LOOP_FILTER,
    GRAY: binding.AV_CODEC_FLAG_GRAY,
    PSNR: binding.AV_CODEC_FLAG_PSNR,
    INTERLACED_DCT: binding.AV_CODEC_FLAG_INTERLACED_DCT,
    LOW_DELAY: binding.AV_CODEC_FLAG_LOW_DELAY,
    GLOBAL_HEADER: binding.AV_CODEC_FLAG_GLOBAL_HEADER,
    BITEXACT: binding.AV_CODEC_FLAG_BITEXACT,
    AC_PRED: binding.AV_CODEC_FLAG_AC_PRED,
    INTERLACED_ME: binding.AV_CODEC_FLAG_INTERLACED_ME,
    CLOSED_GOP: binding.AV_CODEC_FLAG_CLOSED_GOP
  },
  formatFlags: {
    SHOW_IDS: binding.AVFMT_SHOW_IDS,
    GENERIC_INDEX: binding.AVFMT_GENERIC_INDEX,
    TS_DISCONT: binding.AVFMT_TS_DISCONT,
    NOBINSEARCH: binding.AVFMT_NOBINSEARCH,
    NOGENSEARCH: binding.AVFMT_NOGENSEARCH,
    NO_BYTE_SEEK: binding.AVFMT_NO_BYTE_SEEK,
    SEEK_TO_PTS: binding.AVFMT_SEEK_TO_PTS,
    GLOBALHEADER: binding.AVFMT_GLOBALHEADER,
    VARIABLE_FPS: binding.AVFMT_VARIABLE_FPS,
    NODIMENSIONS: binding.AVFMT_NODIMENSIONS,
    NOSTREAMS: binding.AVFMT_NOSTREAMS,
    TS_NONSTRICT: binding.AVFMT_TS_NONSTRICT,
    TS_NEGATIVE: binding.AVFMT_TS_NEGATIVE,
    NOFILE: binding.AVFMT_NOFILE,
    NEEDNUMBER: binding.AVFMT_NEEDNUMBER,
    NOTIMESTAMPS: binding.AVFMT_NOTIMESTAMPS
  },
  seek: {
    SIZE: binding.AVSEEK_SIZE,
    FORCE: binding.AVSEEK_FORCE,
    CUR: binding.SEEK_CUR,
    SET: binding.SEEK_SET,
    END: binding.SEEK_END
  },
  packetSideDataType: {
    PALETTE: binding.AV_PKT_DATA_PALETTE,
    NEW_EXTRADATA: binding.AV_PKT_DATA_NEW_EXTRADATA,
    PARAM_CHANGE: binding.AV_PKT_DATA_PARAM_CHANGE,
    H263_MB_INFO: binding.AV_PKT_DATA_H263_MB_INFO,
    REPLAYGAIN: binding.AV_PKT_DATA_REPLAYGAIN,
    DISPLAYMATRIX: binding.AV_PKT_DATA_DISPLAYMATRIX,
    STEREO3D: binding.AV_PKT_DATA_STEREO3D,
    AUDIO_SERVICE_TYPE: binding.AV_PKT_DATA_AUDIO_SERVICE_TYPE,
    QUALITY_STATS: binding.AV_PKT_DATA_QUALITY_STATS,
    FALLBACK_TRACK: binding.AV_PKT_DATA_FALLBACK_TRACK,
    CPB_PROPERTIES: binding.AV_PKT_DATA_CPB_PROPERTIES,
    SKIP_SAMPLES: binding.AV_PKT_DATA_SKIP_SAMPLES,
    JP_DUALMONO: binding.AV_PKT_DATA_JP_DUALMONO,
    STRINGS_METADATA: binding.AV_PKT_DATA_STRINGS_METADATA,
    SUBTITLE_POSITION: binding.AV_PKT_DATA_SUBTITLE_POSITION,
    MATROSKA_BLOCKADDITIONAL: binding.AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL,
    WEBVTT_IDENTIFIER: binding.AV_PKT_DATA_WEBVTT_IDENTIFIER,
    WEBVTT_SETTINGS: binding.AV_PKT_DATA_WEBVTT_SETTINGS,
    METADATA_UPDATE: binding.AV_PKT_DATA_METADATA_UPDATE,
    MPEGTS_STREAM_ID: binding.AV_PKT_DATA_MPEGTS_STREAM_ID,
    MASTERING_DISPLAY_METADATA: binding.AV_PKT_DATA_MASTERING_DISPLAY_METADATA,
    SPHERICAL: binding.AV_PKT_DATA_SPHERICAL,
    CONTENT_LIGHT_LEVEL: binding.AV_PKT_DATA_CONTENT_LIGHT_LEVEL,
    A53_CC: binding.AV_PKT_DATA_A53_CC,
    ENCRYPTION_INIT_INFO: binding.AV_PKT_DATA_ENCRYPTION_INIT_INFO,
    ENCRYPTION_INFO: binding.AV_PKT_DATA_ENCRYPTION_INFO,
    AFD: binding.AV_PKT_DATA_AFD,
    PRFT: binding.AV_PKT_DATA_PRFT,
    ICC_PROFILE: binding.AV_PKT_DATA_ICC_PROFILE,
    DOVI_CONF: binding.AV_PKT_DATA_DOVI_CONF,
    S12M_TIMECODE: binding.AV_PKT_DATA_S12M_TIMECODE,
    DYNAMIC_HDR10_PLUS: binding.AV_PKT_DATA_DYNAMIC_HDR10_PLUS,
    IAMF_MIX_GAIN_PARAM: binding.AV_PKT_DATA_IAMF_MIX_GAIN_PARAM,
    IAMF_DEMIXING_INFO_PARAM: binding.AV_PKT_DATA_IAMF_DEMIXING_INFO_PARAM,
    IAMF_RECON_GAIN_INFO_PARAM: binding.AV_PKT_DATA_IAMF_RECON_GAIN_INFO_PARAM,
    AMBIENT_VIEWING_ENVIRONMENT:
      binding.AV_PKT_DATA_AMBIENT_VIEWING_ENVIRONMENT,
    FRAME_CROPPING: binding.AV_PKT_DATA_FRAME_CROPPING,
    LCEVC: binding.AV_PKT_DATA_LCEVC,
    '3D_REFERENCE_DISPLAYS': binding.AV_PKT_DATA_3D_REFERENCE_DISPLAYS,
    RTCP_SR: binding.AV_PKT_DATA_RTCP_SR,
    NB: binding.AV_PKT_DATA_NB
  }
}

exports.toPixelFormat = function toPixelFormat(format) {
  if (typeof format === 'number') return format

  if (typeof format === 'string') {
    if (format in exports.pixelFormats === false) {
      throw errors.UNKNOWN_PIXEL_FORMAT(`Unknown pixel format '${format}'`)
    }

    return exports.pixelFormats[format]
  }

  throw new TypeError(
    `Pixel format must be a number or string. Received ${typeof format} (${format})`
  )
}

exports.toSampleFormat = function toSampleFormat(format) {
  if (typeof format === 'number') return format

  if (typeof format === 'string') {
    if (format in exports.sampleFormats === false) {
      throw errors.UNKNOWN_SAMPLE_FORMAT(`Unknown sample format '${format}'`)
    }

    return exports.sampleFormats[format]
  }

  throw new TypeError(
    `Sample format must be a number or string. Received ${typeof format} (${format})`
  )
}

exports.toChannelLayout = function toChannelLayout(layout) {
  if (typeof layout === 'number') return layout

  if (typeof layout === 'string') {
    if (layout in exports.channelLayouts === false) {
      throw errors.UNKNOWN_CHANNEL_LAYOUT(`Unknown channel layout '${layout}'`)
    }

    return exports.channelLayouts[layout]
  }

  throw new TypeError(
    `Channel layout must be a number or string. Received ${typeof layout} (${layout})`
  )
}

exports.getSampleFormatName = function (sampleFormat) {
  return binding.getSampleFormatNameByID(sampleFormat)
}
